#!/bin/bash

#PBS -M MPI
#PBS -joe
#PBS -o run_tests.out
#PBS -q teaching
#PBS -l epilogue=~ggdagw/epilogue.sh
#PBS -l nodes=1:ppn=1,walltime=01:00:00

#! Mail to user if job aborts
#PBS -m a

application="./run_tests.py"

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following machines:
echo `cat $PBS_NODEFILE | uniq`

numnodes=`wc $PBS_NODEFILE | awk '{ print $1 }'`

export OMP_NUM_THREADS=$numnodes

#! Run script
source env_py3.sh
python $application 
source env.sh
