#!/bin/bash

#PBS -N ocl_wgs128_256x256
#PBS -joe
#PBS -o ./tests/test16/output_wgs128_256x256.out
#PBS -q teaching
#PBS -l epilogue=~ggdagw/epilogue.sh
#PBS -l nodes=1:gpus=1,walltime=00:10:00

#! Mail to user if job aborts
#PBS -m a

# Select the GPU that we've been allocated
device=$(cat $PBS_GPUFILE)
device=${device#*gpu}
export OCL_DEVICE=$device

#! application name
application="./d2q9-bgk"

#! Run options for the application
options="input_256x256.params ./tests/test16/obs_256x256_0.30.dat 128"

###############################################################
### You should not have to change anything below this line ####
###############################################################

#! change the working directory (default is home directory)

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following machines:
echo `cat $PBS_NODEFILE | uniq`
echo "Using GPU at index $device"

numcores=`wc $PBS_NODEFILE | awk '{ print $1 }'`

#! Run the executable
$application $options
